### ISSUE TITLE
OSError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by yxliu-T** [cryoFIT/cryo_fit_install#1]
Hi,
I am trying to install cryofit to phenix on Mac OS 10.15 Catalina. The installation failed when I use "libtbx.configure cryo_fit". In terminal, the error message is pasted as follows,
Traceback (most recent call last):
  File "/Applications/phenix-1.17.1-3660/modules/cctbx_project/libtbx/env_config.py", line 2741, in <module>
    warm_start(sys.argv)
  File "/Applications/phenix-1.17.1-3660/modules/cctbx_project/libtbx/env_config.py", line 2699, in warm_start
    env.refresh()
  File "/Applications/phenix-1.17.1-3660/modules/cctbx_project/libtbx/env_config.py", line 1816, in refresh
    self.write_lib_dispatcher_head()
  File "/Applications/phenix-1.17.1-3660/modules/cctbx_project/libtbx/env_config.py", line 1356, in write_lib_dispatcher_head
    target_file=self.under_build(target_file, return_relocatable_path=True))
  File "/Applications/phenix-1.17.1-3660/modules/cctbx_project/libtbx/env_config.py", line 1252, in write_bin_sh_dispatcher
    target_file.chmod(0o755)
  File "/Applications/phenix-1.17.1-3660/modules/cctbx_project/libtbx/path.py", line 283, in chmod
    return os.chmod(abs(self), *args, **kwds)
OSError: [Errno 1] Operation not permitted: '/Applications/phenix-1.17.1-3660/build/dispatcher_head.sh'

I have set full disk access for terminal and have read&write permission for both the build and modules directories under phenix folder (as well as the dispatcher_head.sh file). I am not familiar with computer language and would be grateful if someone can help! Thank you.

**Comment by nwmoriarty** [comment]
Has anyone answered this question for you?

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909      Web  : CCI.LBL.gov
ORCID : orcid.org/0000-0001-8857-9464

**Comment by kimdn** [comment]
Hello,

I just did https://www.phenix-online.org/documentation/tutorials/cryo_fit_install.html#id3
which is about cloning cryo_fit and libtbx.configure cryo_fit (so that phenix can recognize cryo_fit).

It cloned well and linked well as

`...
Using /Users/kimd999/bin/phenix-1.19rc2-4022/conda_base/lib/python2.7/site-packages
Finished processing dependencies for iota==1.4.20
Processing: "/Users/kimd999/bin/phenix-1.19rc2-4022/build/exe_dev"
Done.`
--

Currently, I use macOS 10.14.6.

Unfortunately, my employer doesn't allow me to upgrade my macbook's OS, so I can't reproduce your error in Mac OS 10.15 Catalina.

I've installed cryo_fit many times (>100) in various macOS and linux systems.
Mostly, it was fine.

My current hunch feeling is that Mac OS 10.15 Catalina changes some authority over
/Applications/....sh

Can you install phenix in non-Applications folder?
For example, as in
https://www.phenix-online.org/documentation/install-setup-run.html
just
```
tar xvf phenix-installer-<version>-<platform>.tar
cd phenix-installer-<version>
./install --prefix=<directory>  
```

here the "directory" could be for example, /Users/kimd999/bin

Even if you install phenix in non-Applications folder (like /Users/kimd999/bin),
all commandline and GUI functions will work. Sometimes macOS indexing of PHENIX GUI executables may take some time, but pretty soon it will allow you to access newly installed PHENIX gui automatically.

I think that if you reply to this github post, it will email me directly.
But if you prefer, you can email me as well (doonam.kim@pnnl.gov).

Please let me know how it goes.
If the above method (alternative installation path) doesn't work, I will see what I can do (I may ask my IT support to lend me some new macbook. Additionally, my personal macbook will arrive in early March so I will check macOS of it).

best,
Doo Nam

**Comment by yxliu-T** [comment]
Thank you for your suggestions. The previous OSerror was indeed due to Mac OS 10.15 Catalina authority issue, which could be resolved using sudo. I also re-installed phenix as instructed under /Users/yixinliu/ and continued to install cryo_fit. The process went well until I do:
python /Users/yixinliu/phenix-1.19.1-4122/modules/cryo_fit/files_for_steps/0_install_cryo_fit/install_cryo_fit.py ~/Downloads/gromacs-4.5.5_cryo_fit.zip /Users/yixinliu/CryoFit 

Several errors and warnings occurred and the installation wasn't successful. /cryo_fit/bin/ was not created in /cryo_fit/ directory. I copied here some problems that occurred. I can also copy the warnings and error messages here if it is helpful.

1. make command: make -j 3 
        This did not return "Nothing to be done for `all-am'", but with  inflating: __MACOSX/gromacs-4.5.5_cryo_fit/._src; inflating: __MACOSX/._gromacs-4.5.5_cryo_fit  
2. In the end, it returned:
make[2]: *** [md.o] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1 
3. Not successful installation because cryo_fit can't find  /Users/yixinliu/CryoFit/cryo_fit/bin/mdrun
