### ISSUE TITLE
libtbx.configure cryo_fit permission denied while accessing phenix

### ISSUE THREAD

**Issue by CFDavidHou** [cryoFIT/cryo_fit_install#2]
Hi,

I have a quick question. I encountered error while installing cryo_FIT.

I am able to do 1. install Phenix and 2. link cryo_FIT to phenix step one, but unable to do libtbx.configure cryo_fit

My phenix is installed at /usr/local/ as default. Is there anything I have overlooked?

Thank you!
```
$ libtbx.configure cryo_fit
Traceback (most recent call last):
  File "/usr/local/phenix-1.20-4459/modules/cctbx_project/libtbx/env_config.py", line 3212, in <module>
    warm_start(sys.argv)
  File "/usr/local/phenix-1.20-4459/modules/cctbx_project/libtbx/env_config.py", line 3117, in warm_start
    _warm_start(env, args)
  File "/usr/local/phenix-1.20-4459/modules/cctbx_project/libtbx/env_config.py", line 3087, in _warm_start
    env.refresh()
  File "/usr/local/phenix-1.20-4459/modules/cctbx_project/libtbx/env_config.py", line 2213, in refresh
    completed_file_name.remove()
  File "/usr/local/phenix-1.20-4459/modules/cctbx_project/libtbx/path.py", line 275, in remove
    if self.exists(): os.remove(abs(self))
OSError: [Errno 13] Permission denied: '/usr/local/phenix-1.20-4459/build/libtbx_refresh_is_completed'
```

**Comment by nwmoriarty** [comment]
It looks like you don't have write access to the /usr/local/phenix-1.20-4459/build/libtbx_refresh_is_completed file/directory.
